#Client2_index:
#  path:     /
#  defaults: { _controller: "MyAppEstoreBundle:Client:listeProduit" }
#  methods:  GET
#
#Client2_show:
#  path:     /{id}/show
#  defaults: { _controller: "MyAppEstoreBundle:Client:show" }
#  methods:  GET
#
#Client2_new:
#  path:     /new
#  defaults: { _controller: "MyAppEstoreBundle:Client:new" }
#  methods:  [GET, POST]
#
#Client2_edit:
#  path:     /{id}/edit
#  defaults: { _controller: "MyAppEstoreBundle:Client:edit" }
#  methods:  [GET, POST]
#
#Client2_delete:
#  path:     /{id}/delete
#  defaults: { _controller: "MyAppEstoreBundle:Client:delete" }
#  methods:  DELETE
