Client_index:
    path:     /
    defaults: { _controller: "MyAppEstoreBundle:Client:index" }
    methods:  GET

Client_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppEstoreBundle:Client:show" }
    methods:  GET

Client_new:
    path:     /new
    defaults: { _controller: "MyAppEstoreBundle:Client:new" }
    methods:  [GET, POST]

Client_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppEstoreBundle:Client:edit" }
    methods:  [GET, POST]

Client_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppEstoreBundle:Client:delete" }
    methods:  DELETE
