yes_index:
    path:     /
    defaults: { _controller: "MyAppEstoreBundle:magasin:index" }
    methods:  GET

yes_show:
    path:     /{id}/show
    defaults: { _controller: "MyAppEstoreBundle:magasin:show" }
    methods:  GET

yes_new:
    path:     /new
    defaults: { _controller: "MyAppEstoreBundle:magasin:new" }
    methods:  [GET, POST]

yes_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyAppEstoreBundle:magasin:edit" }
    methods:  [GET, POST]

yes_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyAppEstoreBundle:magasin:delete" }
    methods:  DELETE
