<?php

namespace MyApp\EstoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoitureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureRepository extends EntityRepository
{
    public function findVoitureByName($param){

        $query = $this->createQueryBuilder('v');
        $query->where("v.nom=:nom")
            ->setParameter('nom',$param);
        //->setParameter('mention','excellent');
        return $query->getQuery()->getResult();
    }
    public function findVoitureByName2($arg){
        $requette = $this->getEntityManager()->createQuery("SELECT  v FROM MyAppEstoreBundle:Voiture v 
        WHERE v.nom=$arg");
        // $requette->execute();
        return  $requette->getResult();

    }


}
